# Generated by Django 3.1.7 on 2021-03-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210320_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginCustomer',
        ),
        migrations.AlterField(
            model_name='vendorcustomer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorcustomer',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
