# Generated by Django 3.1.7 on 2021-04-15 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userCustomer',
            fields=[
                ('full_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='vendorCustomer',
            fields=[
                ('full_name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('camera_image', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/products/')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20, null=True)),
                ('last_name', models.CharField(default='', max_length=20, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=15)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('state', models.CharField(default='', max_length=20, null=True)),
                ('rent_date', models.DateField(default=datetime.datetime.today)),
                ('return_date', models.DateField(default=datetime.datetime.today)),
                ('order_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.usercustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
            ],
        ),
    ]
