# Generated by Django 3.1.7 on 2021-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorcustomer',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendorcustomer',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
