# Generated by Django 3.1.7 on 2021-04-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
