# Generated by Django 3.1.7 on 2021-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='rentdate',
            new_name='rent_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='returndate',
            new_name='return_date',
        ),
    ]
